from django.urls import path
from .views import (
    accueil, connexion, inscription, deconnexion,
    dashboard, create_propriete, read_propriete, read_user_properties,
    read_properties_dispo, read_all_propriete, update_propriete, delete_propriete,
    demander_location, autoriser_location, liste_locations,
    liste_factures, payer_facture, generer_facture_mois,
    gerer_documents,
    liste_interventions, creer_intervention, modifier_statut_intervention,
)

urlpatterns = [
    path('', accueil, name='accueil'),
    path('locative/user/dashboard/', dashboard, name='dashboard'),
    path('locative/user/connexion/', connexion, name='connexion'),
    path('locative/user/inscription/', inscription, name='inscription'),
    path('locative/user/deconnexion/', deconnexion, name='deconnexion'),
    path('locative/facture/liste/', liste_factures, name='liste_factures'),
    path('locative/facture/payer/<int:location_id>/', payer_facture, name='payer_facture'),
    path('locative/facture/generer/<int:location_id>/', generer_facture_mois, name='generer_facture_mois'),
    path('locative/locations/liste/', liste_locations, name='liste_locations'),
    path('locative/location/demande/<int:propriete_id>/', demander_location, name='demander_location'),
    path('locative/location/autorisation/<int:location_id>/', autoriser_location, name='autoriser_location'),
    path('locative/gestion/documents/<int:propriete_id>/', gerer_documents, name='gerer_documents'),
    path('locative/propriete/create/<int:user_id>/', create_propriete, name='create_propriete'),
    path('locative/propriete/read/<int:propriete_id>/', read_propriete, name='read_propriete'),
    path('locative/propriete/read/one/', read_user_properties, name='read_user_properties'),
    path('locative/propriete/read/dispo/', read_properties_dispo, name='read_properties_dispo'),
    path('locative/propriete/read/all/', read_all_propriete, name='read_all_propriete'),
    path('locative/propriete/update/<int:propriete_id>/', update_propriete, name='update_propriete'),
    path('locative/propriete/delete/<int:propriete_id>/', delete_propriete, name='delete_propriete'),
    path('locative/interventions/', liste_interventions, name='liste_interventions'),
    path('locative/intervention/creer/<int:propriete_id>/', creer_intervention, name='creer_intervention'),
    path('locative/intervention/<int:intervention_id>/statut/', modifier_statut_intervention, name='modifier_statut_intervention'),
]