# Generated by Django 4.2.7 on 2024-01-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLocative', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='montant',
            new_name='montantFacture',
        ),
        migrations.AddField(
            model_name='location',
            name='montantLocation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propriete',
            name='demande_allocation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propriete',
            name='n',
            field=models.IntegerField(default=0),
        ),
    ]
