# Generated by Django 5.2.3 on 2026-02-22 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLocative', '0003_plateforme_complete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-date_upload'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_facturation'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='propriete',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Propriété', 'verbose_name_plural': 'Propriétés'},
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(upload_to='documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='propriete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='gestionLocative.propriete'),
        ),
        migrations.AlterField(
            model_name='document',
            name='titre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='document',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montantFacture',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='periode',
            field=models.CharField(blank=True, help_text='Période concernée (format AAAA-MM)', max_length=7),
        ),
        migrations.AlterField(
            model_name='facture',
            name='propriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='gestionLocative.propriete'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='message_demande',
            field=models.TextField(blank=True, help_text='Message du demandeur'),
        ),
        migrations.AlterField(
            model_name='location',
            name='montantLocation',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Montant total de la location (calculé à l'acceptation)", max_digits=12),
        ),
        migrations.AlterField(
            model_name='location',
            name='propriete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='gestionLocative.propriete'),
        ),
        migrations.AlterField(
            model_name='location',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='charges_comprises',
            field=models.BooleanField(default=False, help_text='Charges incluses dans le loyer'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='garantie',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Dépôt de garantie', max_digits=10),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='locataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietes_louees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Loyer mensuel', max_digits=12),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='montant_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Montant des charges si non comprises', max_digits=8),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='n',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de demandes refusées (nb_refus)'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='nb_chambre',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='nb_etage',
            field=models.CharField(blank=True, help_text="Étage ou nombre d'étages", max_length=20),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='proprietaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietes_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='surface',
            field=models.DecimalField(decimal_places=2, help_text='Surface en m²', max_digits=8),
        ),
    ]
