# Generated by Django 5.2.3 on 2026-02-23 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLocative', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(choices=[('PROPRIO', 'Propriétaire'), ('LOCA', 'Locataire')], default='LOCA', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='gestionLocative.user'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='gestionLocative.user'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='demandeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_demandees', to='gestionLocative.user'),
        ),
        migrations.AlterField(
            model_name='location',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='gestionLocative.user'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='locataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietes_louees', to='gestionLocative.user'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='proprietaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietes_owned', to='gestionLocative.user'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
